name: CI (Test with Vitest)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # Atau versi lain yang Anda inginkan

    - name: Install dependencies
      run: yarn install

    - name: Run tests with Vitest
      run: npm test # Ini akan menjalankan script "test": "vitest" dari package.json